---
- name: Adds docker gpg key
  apt_key: keyserver=hkp://pgp.mit.edu id=58118E89F3A912897C070ADBF76221572C52609D

- name: add docker repository
  shell: echo deb https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list

- name: purges old docker repos
  command: apt-get purge lxc-docker*
  ignore_errors: true

- name: Updated repository verification
  command: apt-cache policy docker-engine
  ignore_errors: true

- name: Install dependencies
  apt:
      name=linux-image-generic-lts-trusty
      update_cache=yes

- name: reboot system
  command: reboot

- name: waiting for system to reboot
  local_action:
      module: wait_for
        port=22
        host={{ansible_ssh_host}}
        state=started
        delay=45
        timeout=300
  become: false

- name: Install dependencies
  apt:
      name=docker-engine
      update_cache=yes

- name: add user to docker group
  user: name=ubuntu groups=docker append=yes
  notify:
    - Kill all ssh connections